base:
  config:
    nacos:
      hostname: com.fx.shop.cloud
      port: 8848
      username: nacos
      password: nacos


spring:
  application:
    name: business-reg
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
        username: ${base.config.nacos.username}
        password: ${base.config.nacos.password}

dubbo:
  application:
    # Serializable 接口检查模式，Dubbo 中默认配置为 `true` 开启检查
    check-serializable: false
    # 检查模式分为三个级别：STRICT 严格检查，WARN 告警，DISABLE 禁用 3.2 版本中默认为 STRICT 严格检查级别
    serialize-check-status: DISABLE
  scan:
    base-packages: com.fx.shop.provider.controller
  protocol:
    name: dubbo
    port: -1
#    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}:${base.config.nacos.port}?username=${base.config.nacos.username}&password=${base.config.nacos.password}

server:
  # ${random.int[9000,9999]} 随机端口
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
