base:
  config:
    tidb:
      hostname: localhost
      port: 3306
    nacos:
      hostname: com.fx.shop.cloud
      port: 8848
      username: nacos
      password: nacos
    sentile:
      hostname: localhost
      port: 8080
    redis:
      hostname: localhost
      port: 6380

spring:
  application:
    name: business-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
        username: ${base.config.nacos.username}
        password: ${base.config.nacos.password}
    sentinel:
      transport:
        dashboard: ${base.config.sentile.hostname}:${base.config.sentile.port}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/shop_oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 18786711938
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#  redis:
#    host: ${base.config.redis.hostname}
#    port: ${base.config.redis.port}
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-wait: -1ms
#        max-active: 8

dubbo:
  application:
    # Serializable 接口检查模式，Dubbo 中默认配置为 `true` 开启检查
    check-serializable: false
    # 检查模式分为三个级别：STRICT 严格检查，WARN 告警，DISABLE 禁用 3.2 版本中默认为 STRICT 严格检查级别
    serialize-check-status: DISABLE
  scan:
    base-packages: com.fx.shop.business.controller, com.fx.shop.business.service
  protocol:
    name: dubbo
    port: -1
#    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}:${base.config.nacos.port}?username=${base.config.nacos.username}&password=${base.config.nacos.password}

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret